const roundOnePrompts = [
  'Suspects',
  'Clues',
  'Deadly Sins',
  'Planets to Explore',
  'Alien Species',
  'Technological Advancements',
  'Magical Creatures',
  'Ancient Artifacts',
  'Enchanted Realms',
  'Love Letters',
  'First Dates',
  'Relationship Goals',
  'Creepy Houses',
  'Fears',
  'Curses',
  'Family Secrets',
  'Regrets',
  'Life Lessons',
  'Treacherous Journeys',
  'Deadly Challenges',
  'Hidden Temples',
  'High School Cliques',
  'Coming-of-Age Moments',
  'Teenage Struggles',
  'Historical Events',
  'Historical Figures',
  'Cultural Traditions',
  'Ridiculous Jobs',
  'Funny Friends',
  'Comedic Misadventures',
  'Dystopian Societies',
  'Rebellious Acts',
  'Survival Strategies',
  'Steampunk Inventions',
  'Airship Voyages',
  'Steampunk Cities',
  'Olympian Gods',
  'Mythical Creatures',
  'Ancient Prophecies',
  'Survival Skills',
  "Collector's Dilemma",
  "Survivor's Inventory",
  "Time Traveler's Log",
  "Chef's Secret Recipe Book",
  'Heist Planner',
  "Botanist's Discovery",
  'Star Chart',
  'Lost Children',
  'Dream Journal',
  "Ghost Hunter's Guide",
  "Alchemist's Formulae",
  "Explorer's Map",
  "Ship's Manifest",
  "Dragon's Hoard",
  "Witch's Grimoire",
  "Inventor's Blueprints",
  "Prophecy's Conditions",
  "Detective's Suspects",
  "Rebel's Targets",
  "Musician's Setlist",
  'Time Capsule',
  "Festival's Attractions",
  "Art Thief's Wishlist",
  "Librarian's Index",
  "Smuggler's Cargo",
  "Knight's Quests",
  "Scientist's Experiments",
  "Secret Society's Members",
  'Zoo of Mythical Creatures',
  "Traveler's Bucket List",
  'Cursed Objects',
  "Healer's Remedies",
  "Gambler's Bets",
  "Assassin's Contracts",
  "Fashion Designer's Collection",
  "Treasure Map's X's",
  "Ritual's Steps",
  "Spy's Codes",
  "Pilgrim's Shrines",
  "Doomsday Prepper's Supplies",
  'Lost City Secrets',
  'Forgotten Time Travel',
  'Dark Magic Spells',
  'Ancient Alien Artifacts',
  'Hidden World Portals',
  'Deadly Sinister Forces',
  'Mysterious Future Events',
  'Celestial Being Encounters',
  'Steampunk Revolution Plans',
  'Haunted House Legends',
  'Supernatural Power Struggles',
  'Dystopian Society Rules',
  'Apocalyptic Survival Tactics',
  'Cybernetic Uprising Leaders',
  'Paranormal Activity Hunters',
  "Time Traveler's Dilemma",
  'Alternate Reality Shift',
  'Quantum Physics Experiments',
  'Epic Quest Beginnings',
  'Treacherous Journey Routes',
  'Sinister Plot Twists',
  'Ancient Prophecy Fulfillment',
  'Forgotten Past Memories',
  'Bitter Rivalry Frenzy',
  'Hidden Truth Revealed',
  'Deadly Secret Keepers',
  'Mysterious Stranger Arrivals',
  'Ghostly Encounter Nights',
  'Demon Slayer Training',
  'Virtual Reality Dreams',
  'Futuristic Society Norms',
  'Cosmic Horror Encounters',
  'Steampunk Invention Creations',
  'Rogue Agent Missions',
  'Unseen Enemy Tactics',
  'Celestial War Battles',
  'Ancient Curse Breakers',
  'Time Warp Adventures',
  'Alternate Dimension Journeys',
  'Quantum Leap Consequences',
  'Lost City Secrets',
  'Forgotten Time Travel',
  'Dark Magic Spells',
  'Ancient Alien Artifacts',
  'Hidden World Portals',
  'Deadly Sinister Forces',
  'Mysterious Future Events',
  'Celestial Being Encounters',
  'Steampunk Revolution Plans',
  'Haunted House Legends',
  'Supernatural Power Struggles',
  'Dystopian Society Rules',
  'Apocalyptic Survival Tactics',
  'Cybernetic Uprising Leaders',
  'Paranormal Activity Hunters',
  "Time Traveler's Dilemma",
  'Alternate Reality Shift',
  'Quantum Physics Experiments',
  'Epic Quest Beginnings',
  'Treacherous Journey Routes',
  'Sinister Plot Twists',
  'Ancient Prophecy Fulfillment',
  'Forgotten Past Memories',
  'Bitter Rivalry Frenzy',
  'Hidden Truth Revealed',
  'Deadly Secret Keepers',
  'Mysterious Stranger Arrivals',
  'Ghostly Encounter Nights',
  'Demon Slayer Training',
  'Virtual Reality Dreams',
  'Futuristic Society Norms',
  'Cosmic Horror Encounters',
  'Steampunk Invention Creations',
  'Rogue Agent Missions',
  'Unseen Enemy Tactics',
  'Celestial War Battles',
  'Ancient Curse Breakers',
  'Time Warp Adventures',
  'Alternate Dimension Journeys',
  'Quantum Leap Consequences',
  'Islands',
  'Secrets',
  'Quests',
  'Masks',
  'Portals',
  'Heists',
  'Rebellions',
  'Ruins',
  'Visions',
  'Whispers',
  'Shadows',
  'Curses',
  'Prophecies',
  'Discoveries',
  'Deceptions',
  'Revolutions',
  'Rivals',
  'Enigmas',
  'Odysseys',
  'Illusions',
  'Conspiracies',
  'Chronicles',
  'Trials',
  'Tribes',
  'Omens',
  'Invasions',
  'Uprisings',
  'Paradoxes',
  'Escapes',
  'Encounters',
  'Legacy',
  'Vortex',
  'Renegades',
  'Specters',
  'Fugitives',
  'Aberrations',
  'Conquests',
  'Deities',
  'Cataclysms',
  'Eternity',
  'Lost City Secret Gates',
  "Forgotten Time Traveler's Journey",
  'Dark Magic Spellbound Creatures',
  'Ancient Alien Artifact Hunters',
  'Hidden World Portal Keys',
  'Deadly Sinister Force Encounters',
  'Mysterious Future Event Horizons',
  'Celestial Being Encounter Teams',
  "Steampunk Revolution Inventors' Guild",
  'Haunted House Legacy Secrets',
  'Supernatural Power Struggle Wars',
  'Dystopian Society Rebellion Leaders',
  'Apocalyptic Survival Tactics Squad',
  'Cybernetic Uprising Rebel Forces',
  'Paranormal Activity Investigation Teams',
  "Time Traveler's Dilemma Solutions",
  'Alternate Reality Shift Agents',
  'Quantum Physics Experiment Teams',
  'Epic Quest Hero Origins',
  'Treacherous Journey Route Finders',
  'Sinister Plot Twist Masters',
  'Ancient Prophecy Fulfillment Teams',
  'Forgotten Past Memory Keepers',
  'Bitter Rivalry Frenzy Fighters',
  'Hidden Truth Revelation Agents',
  'Deadly Secret Keeper Societies',
  'Mysterious Stranger Arrival Teams',
  'Ghostly Encounter Night Watch',
  'Demon Slayer Training Academies',
  'Virtual Reality Dreamscapes',
  'Futuristic Society Norm Enforcers',
  'Cosmic Horror Encounter Units',
  'Steampunk Invention Convention',
  'Rogue Agent Mission Controllers',
  'Unseen Enemy Tactical Teams',
  'Celestial War Battle Command',
  'Ancient Curse Breaker Squads',
  'Time Warp Adventure Teams',
  'Alternate Dimension Journey Agents',
  'Quantum Leap Consequence Managers',
  'Ancient library',
  'forbidden knowledge',
  'coded message',
  'decipher quest',
  'Dystopian city',
  'bioluminescent plants',
  'rebel whispers',
  'hidden network',
  'Interstellar travel',
  'first contact',
  'cultural misunderstandings',
  'peace treaty',
  'Haunted house',
  'hidden passage',
  'spectral cries',
  'forgotten memories',
  'Cybernetic detective',
  'malfunctioning AI',
  'lost memories',
  'hidden identity',
  'Space pirates',
  'stolen artifact',
  'galactic chase',
  'ancient prophecy',
  'Time traveler',
  'alternate timeline',
  'desperate message',
  'save the future',
  'Culinary competition',
  'secret ingredient',
  'unexpected outcome',
  'culinary fame',
  'Superhero team',
  'dwindling powers',
  'alien threat',
  'city under siege',
  'Fairy tale retelling',
  'rebellious princess',
  'forbidden magic',
  'enchanted forest',
  'Dragons hoard',
  'forgotten artifact',
  'fearless scholar',
  'mythical discovery',
  'Post-apocalyptic wasteland',
  'lone survivor',
  'robotic companion',
  'search for hope',
  'School of magic',
  'forbidden spell',
  'accidental portal',
  'parallel world',
  'Hidden village',
  'mythical creature',
  'ancient prophecy',
  'chosen warrior',
  'Noir detective',
  'cryptic message',
  'dark secret',
  'femme fatale',
  'Murder mystery',
  'locked room',
  'hidden clue',
  'shocking revelation',
  'Haunted ship',
  'restless spirits',
  'buried treasure',
  'stormy seas',
  'Mad scientist',
  'forbidden experiment',
  'unexpected mutation',
  'monstrous creation',
  'High-stakes poker game',
  'hidden agenda',
  'marked cards',
  'winner takes all',
  'Alien invasion',
  'technological marvel',
  'human resistance',
  'unlikely savior',
  'Pop star scandal',
  'leaked recording',
  'career ruined',
  'redemption song',
  'Amnesiac traveler',
  'hidden past',
  'cryptic tattoo',
  'unlocked memories',
  'Hidden vampire society',
  'forbidden love',
  'human sacrifice',
  'hunter uprising',
  'Zombie apocalypse',
  'fortified shelter',
  'dwindling supplies',
  'desperate escape',
  'Space station malfunction',
  'oxygen leak',
  'trapped crew',
  'heroic sacrifice',
  'Virtual reality game',
  'trapped player',
  'blurred reality',
  'fight to escape',
  'Cooking competition sabotage',
  'secret ingredient',
  'unexpected alliance',
  'victory snatched',
  'Art heist',
  'elaborate plan',
  'double agent',
  'priceless masterpiece',
  'Wild West outlaw',
  'hidden bounty',
  'forgotten town',
  'final showdown',
  'Underwater city',
  'bioluminescent creatures',
  'deep-sea mystery',
  'ancient knowledge',
  'Rock band on tour',
  'backstage fight',
  'stolen lyrics',
  'opening act triumph',
  'Haunted amusement park',
  'malfunctioning ride',
  'trapped passengers',
  'chilling laughter',
  'Space colony rebellion',
  'oppressive leader',
  'hidden message',
  'uprising begins',
  'Superhero training academy',
  'underdog student',
  'hidden potential',
  'surprise victory',
  'Haunted antique shop',
  'cursed object',
  'unsuspecting buyer',
  'unleashed nightmare',
  'Culinary school rivalry',
  'stolen recipe',
  'secret ingredient',
  'unexpected twist',
  'Time-traveling historian',
  'accidental paradox',
  'lost love',
  'desperate return',
  'Dystopian city',
  'forbidden love',
  'rebellion ignited',
  'fight for freedom',
  'High-stakes poker tournament',
  'skilled bluffer',
  'unexpected opponent',
  'all-in bet',
  'Ancient library',
  'sentient books',
  'forbidden knowledge',
  'awakened power',
  'Colors of the Rainbow',
  'Types of Magical Creatures',
  'Planets in Our Solar',
  'Foods from Around World',
  'Forms of Poetry Styles',
  'Historical Events Timeline List',
  'Mythical Beasts and Legends',
  'Types of Musical Genres',
  'World Landmarks and Wonders',
  'Famous Scientists and Theories',
  'Ancient Civilizations and Ruins',
  'Types of Superhero Powers',
  'Foods for Special Diets',
  'Forms of Meditation Practices',
  'Historical Figures and Quotes',
  'Mythical Places and Realms',
  'Types of Martial Arts',
  'World Currencies and Symbols',
  'Famous Artists and Styles',
  'Ancient Myths and Legends',
  'Types of Time Travel',
  'Foods for Different Seasons',
  'Forms of Yoga Practices',
  'Historical Events and Dates',
  'Mythical Creatures and Beasts',
  'Types of Sports and Games',
  'World Languages and Dialects',
  'Famous Writers and Books',
  'Ancient Inventions and Discoveries',
  'Types of Natural Wonders',
  'Foods for Special Occasions',
  'Forms of Dance Styles',
  'Historical Figures and Biographies',
  'Mythical Heroes and Legends',
  'Types of Fantasy Creatures',
  'World Holidays and Celebrations',
  'Famous Musicians and Genres',
  'Ancient Cultures and Traditions',
  'Types of Adventure Activities',
  'Foods from Different Cultures',
  'Forms of Art and Design',
  'Historical Events and Causes',
  'Planets',
  'Superpowers',
  'Musicians',
  'Myths',
  'Cities',
  'Foods',
  'Sports',
  'Historical',
  'Fantasy',
  'Colors',
  'Animals',
  'Inventions',
  'Seasons',
  'Holidays',
  'Heroes',
  'Legends',
  'Creatures',
  'Adventures',
  'Artists',
  'Writers',
  'Scientists',
  'Philosophers',
  'Cultures',
  'Traditions',
  'Landmarks',
  'Wonders',
  'Genres',
  'Styles',
  'Dance',
  'Music',
  'Poetry',
  'Festivals',
  'Rituals',
  'Symbols',
  'Mythology',
  'Fables',
  'Tales',
  'Legends',
  'Dreams',
  'Nightmares',
  'Imagination',
  'Types of Magical Creatures Exist',
  'Planets in Our Solar System',
  'Foods from Around the World',
  'Forms of Poetry and Expression',
  'Historical Events that Shaped Nations',
  'Mythical Beasts and Legendary Stories',
  'Types of Superhero Powers and',
  'Famous Scientists and Their Theories',
  'Ancient Civilizations and Lost Ruins',
  'Types of Musical Instruments and',
  'World Landmarks and Natural Wonders',
  'Famous Artists and Their Masterpieces',
  'Ancient Myths and Forgotten Legends',
  'Types of Time Travel Adventures',
  'Foods for Different Cultural Celebrations',
  'Forms of Meditation and Mindfulness',
  'Historical Figures and Their Quotes',
  'Mythical Places and Hidden Realms',
  'Types of Martial Arts Disciplines',
  'World Currencies and Financial Systems',
  'Famous Writers and Their Novels',
  'Ancient Inventions and Modern Innovations',
  'Types of Natural Disasters and',
  'Foods for Special Dietary Needs',
  'Forms of Dance and Movement',
  'Historical Events and Their Causes',
  'Mythical Heroes and Their Quests',
  'Types of Fantasy and Fiction',
  'World Holidays and Cultural Traditions',
  'Famous Musicians and Their Genres',
  'Ancient Cultures and Forgotten Customs',
  'Types of Adventure and Exploration',
  'Foods from Different Historical Eras',
  'Forms of Art and Creative',
  'Historical Figures and Their Biographies',
  'Mythical Creatures and Their Habitats',
  'Types of Sports and Games Played',
  'World Languages and Their Origins',
  'Famous Philosophers and Their Teachings',
  'Ancient Civilizations and Their Achievements',
  'Galactic Expeditions',
  'Cryptic Messages',
  'Forgotten Lore',
  'Steampunk Dreams',
  'Nebula Nomads',
  'Fractured Realms',
  'Echoing Silences',
  'Whispering Winds',
  'Rustic Charm',
  'Vintage Vibes',
  'Cosmic Horizons',
  'Mystic Arts',
  'Shadowlands Tales',
  'Gilded Ages',
  'Starlight Serenades',
  'Dreamcatcher Journeys',
  'Wilderness Odyssey',
  'Celestial Bodies',
  'Aurora Bloom',
  'Frostbite Frenzy',
  'Sonic Waves',
  'Luminous Paths',
  'Ghosts of Past',
  'Future Frontiers',
  'Quantum Leaps',
  'Mythic Mettle',
  'Interstellar Voyages',
  'Haunted Harmonies',
  'Stormy Weather',
  'Blossoming Worlds',
  'Astral Projections',
  'Crystal Caverns',
  'Nebula Nexus',
  'Fractured Time',
  'Spectral Voices',
  'Retro Revival',
  'Cosmic Rifts',
  'Mystic Miracles',
  'Beyond Time Travel',
  'Cosmic Dreamcatcher Journeys',
  'Forgotten Ancient Ruins',
  'Galactic Expedition Teams',
  'Hidden World Portals',
  'Infinite Space Odyssey',
  'Lost City Explorers',
  'Mysterious Energy Signatures',
  'New World Discoveries',
  'Oceanic Adventure Quests',
  'Parallel Universe Theories',
  'Quantum Leap Forward',
  'Rare Celestial Events',
  'Secret Society Missions',
  'Timeless Wisdom Keepers',
  'Uncharted Territory Ventures',
  'Vast Cosmic Horizons',
  'Wilderness Survival Skills',
  'X-Treme Weather Conditions',
  'Yearning for Adventure',
  'Zephyr Wind Dancers',
  'Astral Plane Travels',
  'Celestial Music Compositions',
  'Dark Matter Realms',
  'Ethereal Dreamscapes Unfold',
  'Futuristic Cityscapes Rise',
  'Gigantic Space Stations',
  'Holographic Reality Shifts',
  'Interdimensional Gateways Open',
  'Journey Through Cosmos',
  'Kinetic Energy Unleashed',
  'Luminous Starlight Paths',
  'Mind-Bending Paradoxes Solved',
  'Nebula Nomad Tribes',
  'Oceanic Abyss Explorers',
  'Planetary Colonization Missions',
];
const roundTwoPrompts = [
  'A magical realm hidden within a modern city',
  'A quest to retrieve a powerful artifact',
  'A rebellion against an evil sorcerer',
  'A mythical creature as a main character',
  'A world where magic has a cost',
  'A space station on the edge of a black hole',
  'A rebellion against an AI overlord',
  'A time traveler stuck in the past',
  'A colony on a distant planet',
  'A mysterious alien encounter',
  'A detective with a unique ability',
  'A murder at a secluded mansion',
  'A missing person case with a twist',
  'A conspiracy theory turned real',
  'A crime scene with no evidence',
  'A haunted house with a dark history',
  'A small town with a sinister secret',
  'A group trapped in a creepy forest',
  'A supernatural entity with a grudge',
  'A cursed object with deadly consequences',
  'A love story set in a small town',
  'A forbidden love affair',
  'A second chance at love',
  'A love triangle with a twist',
  'A romance that defies societal norms',
  'A historical event from a unique perspective',
  'A fictional character in a historical setting',
  'A historical figure with a secret life',
  'A war story from the home front',
  'A historical mystery solved',
  'A treasure hunt with a twist',
  'A journey to a lost city',
  'A group of strangers on a quest',
  'A solo adventurer in a dangerous land',
  'A thrilling heist with unexpected consequences',
  'A world where technology has surpassed humanity',
  'A society with a strict class system',
  'A rebellion against an oppressive government',
  'A mysterious phenomenon with unknown origins',
  'A group of friends on a road trip gone wrong',
  'A person with a unique ability to change the world',
  'A small town with a dark secret',
  'A world where time is currency',
  'A society where memories can be transferred',
  'A mysterious library containing forbidden knowledge',
  'A being with the power to manipulate reality',
  'A realm where emotions take physical form',
  'A machine that can predict the future',
  'A group of individuals with shared dreams',
  'A place where the laws of physics are flexible',
  'A being who has lived forever',
  'A world where thoughts are tangible entities',
  'A ritual to summon an otherworldly entity',
  'A mysterious artifact with unknown purpose',
  'A realm where the collective unconscious is manifest',
  'A being who can communicate with the dead',
  'A world where the fabric of reality is unraveling',
  'A mysterious energy field with transformative power',
  'A place where the past and present converge',
  'A being with the power to bend the elements',
  'A society where the concept of self is fluid',
  'A mysterious portal to another dimension',
  'A being who has transcended human form',
  'A world where the laws of causality are reversed',
  'A mysterious text with hidden meanings',
  'A place where the boundaries of identity are blurred',
  'A being who can manipulate the fabric of space',
  'A world where the concept of time is relative',
  'A mysterious force that defies explanation',
  'A society where the collective consciousness is one',
  'A being who has achieved enlightenment',
  'A world where the laws of physics are mere suggestions',
  'A mysterious realm where the impossible is possible',
  'A being who can see beyond the veil of reality',
  'Color of silence',
  'Shape of forgotten memory',
  'Sound of whispered secret',
  'Texture of dream',
  'Taste of nostalgia',
  'Scent of forgotten place',
  'Feeling of being lost in thought',
  'Weight of single decision',
  'Space between two moments',
  'Echoes of forgotten melody',
  'Shadows cast by doubt',
  'Light that filters through uncertainty',
  'Rhythm of restless mind',
  'Beauty of fragmented thought',
  'Chaos of creative storm',
  'Peace that follows turbulent mind',
  'Fragments of shattered illusion',
  'Whispers of distant truth',
  'Haze of forgotten reality',
  'Clarity of sudden epiphany',
  'Softness of gentle realization',
  'Hardness of harsh truth',
  'Fluidity of changing perspective',
  'Stagnation of fixed mindset',
  'Freedom of open heart',
  'Cages of closed mind',
  'Wings of soaring imagination',
  'Roots of deep connection',
  'Wings of fleeting thought',
  'Anchors of stable foundation',
  'Waves of turbulent sea',
  'Shores of peaceful refuge',
  'Embrace of nothingness',
  'Serenity of empty space',
  'Depth of a single breath',
  'Infinity of a moment',
  'Being trapped in a never-ending loop of time',
  'Finding oneself lost in a labyrinth of thoughts',
  'Standing at the edge of a cliff of uncertainty',
  'Navigating a sea of contradictory emotions',
  'Being suspended in a state of limbo',
  'Trying to grasp a handful of sand',
  'Chasing a fleeting shadow of happiness',
  'Unraveling a knot of tangled memories',
  'Walking through a maze of broken mirrors',
  'Drowning in a ocean of expectations',
  'Hanging by a thread of hope',
  'Lost in a fog of forgotten dreams',
  'Searching for a door in a wall of silence',
  'Climbing a mountain of self-doubt',
  'Dancing on the edge of chaos',
  'Sinking in a quicksand of fear',
  'Flying through a storm of confusion',
  'Swimming in a pool of uncertainty',
  'Crawling through a tunnel of darkness',
  'Balancing on a tightrope of emotions',
  'Sitting in a room of echoing whispers',
  'Trying to hold water in a leaky cup',
  'Chasing a mirage of perfection',
  'Wandering through a desert of loneliness',
  'Stuck in a revolving door of indecision',
  'Falling through a crack in time',
  'Hiding in a closet of secrets',
  'Riding a rollercoaster of emotions',
  'Lost in a library of forgotten knowledge',
  'Trying to find a needle in a haystack of thoughts',
  'A world where time is currency, and the rich are immortal',
  'A society where emotions are outlawed, and feelings are a crime',
  'A reality where memories can be transferred, and identities are fluid',
  'A dimension where the laws of physics are mere suggestions',
  'A realm where the collective unconscious is a tangible force',
  'A place where the boundaries of reality are constantly shifting',
  'A state of being where the self is a multiple entity',
  'A condition where the past, present, and future coexist',
  'A scenario where the concept of truth is a personal choice',
  'A world where the fabric of reality is woven from individual perspectives',
  'A situation where the laws of causality are reversed',
  'A realm where the power of imagination is the only currency',
  'A dimension where the concept of time is a loop',
  'A place where the collective consciousness is a single entity',
  'A state of being where the self is a work of art',
  'A condition where the boundaries of identity are constantly blurring',
  'A scenario where the concept of reality is a social construct',
  'A world where the fabric of space is a tapestry of stories',
  'A situation where the laws of physics are a matter of personal opinion',
  'A realm where the power of creativity is the only force',
  'A dimension where the concept of self is a multiple choice',
  'A place where the collective unconscious is a reservoir of knowledge',
  'A state of being where the self is a dynamic system',
  'A condition where the past, present, and future are intertwined',
  'A scenario where the concept of truth is a moving target',
  'A secret society hiding in plain sight',
  'A mysterious artifact with the power to bend reality',
  'A hidden world within our own, invisible to the naked eye',
  'A mystical realm where the laws of physics are mere suggestions',
  'A group of individuals with the ability to manipulate the fabric of time',
  'A mysterious energy field with the power to transform reality',
  'A place where the collective unconscious is a tangible force',
  'A scenario where the concept of truth is a personal choice',
  'A world where the fabric of reality is woven from individual perspectives',
  'A situation where the laws of causality are reversed',
  'A realm where the power of imagination is the only currency',
  'A dimension where the concept of time is a loop',
  'A place where the collective consciousness is a single entity',
  'A state of being where the self is a work of art',
  'A condition where the boundaries of identity are constantly blurring',
  'A scenario where the concept of reality is a social construct',
  'A world where the fabric of space is a tapestry of stories',
  'A situation where the laws of physics are a matter of personal opinion',
  'A realm where the power of creativity is the only force',
  'A dimension where the concept of self is a multiple choice',
  'A place where the collective unconscious is a reservoir of knowledge',
  'A state of being where the self is a dynamic system',
  'A condition where the past, present, and future are intertwined',
  'A scenario where the concept of truth is a moving target',
  'A mysterious figure with the power to manipulate reality',
  'A hidden text with the secrets of the universe',
  'A mysterious symbol with the power to unlock hidden knowledge',
  'A place where the laws of physics are mere suggestions',
  'A scenario where the concept of time is fluid',
  'A world where the fabric of reality is constantly shifting',
  'A world where cats can talk, but only in French',
  'A society where the currency is emotions, and happiness is a luxury',
  'A reality where gravity only exists on Tuesdays',
  'A dimension where time is currency, and the rich are immortal, but only if they wear funny hats',
  'A place where the laws of physics are determined by a committee of squirrels',
  'A scenario where the concept of truth is decided by a game of rock-paper-scissors',
  'A world where the fabric of reality is made of Play-Doh',
  'A situation where the laws of causality are enforced by a team of ninja accountants',
  'A realm where the power of imagination is fueled by eating pizza',
  'A dimension where the concept of self is a multiple-choice question',
  'A place where the collective unconscious is a giant game of Simon Says',
  'A state of being where the self is a shape-shifting blob of goo',
  'A condition where the boundaries of identity are constantly changing like a kaleidoscope',
  'A scenario where the concept of reality is a choose-your-own-adventure book',
  'A world where the fabric of space is a giant puzzle, and the pieces are made of Jell-O',
  'A situation where the laws of physics are a matter of personal taste',
  'A realm where the power of creativity is fueled by playing the harmonica',
  'A dimension where the concept of time is a never-ending loop of elevator music',
  'A place where the collective unconscious is a giant library of forgotten memories',
  'A state of being where the self is a work of art, created by a team of mischievous monkeys',
  'A condition where the past, present, and future are all happening at the same time, but in different rooms',
  'A scenario where the concept of truth is a moving target, and the only way to hit it is by riding a unicycle',
  'A world where the fabric of reality is made of candy, and the laws of physics are determined by a candy machine',
  'A situation where the laws of causality are enforced by a team of robotic chickens',
  'A realm where the power of imagination is fueled by eating ice cream',
  'A dimension where the concept of self is a puzzle, and the pieces are made of mirrors',
  'A world where politicians are held accountable for their promises',
  'A society where social media influencers are required to disclose their fake followers',
  'A reality where climate change deniers are forced to live on a melting iceberg',
  'A dimension where the wealthy are taxed based on their privilege',
  'A place where the news is required to be truthful and unbiased',
  'A scenario where corporations are held liable for their environmental damage',
  'A world where the education system prioritizes critical thinking over standardized tests',
  "A situation where the government prioritizes the people's needs over corporate profits",
  'A realm where the powerful are held accountable for their actions',
  'A dimension where the truth is valued over alternative facts',
  'A place where the media is required to fact-check before reporting',
  'A state of being where the self is not defined by consumerism',
  'A condition where the boundaries of identity are not limited by societal norms',
  'A scenario where the concept of reality is not distorted by confirmation bias',
  'A world where the fabric of space is not torn apart by political polarization',
  'A situation where the laws of physics are not ignored by climate change deniers',
  'A realm where the power of imagination is not stifled by conformity',
  'A dimension where the concept of time is not wasted on bureaucracy',
  'A place where the collective unconscious is not plagued by systemic injustices',
  'A state of being where the self is not trapped in a cycle of consumption',
  'A condition where the past, present, and future are not distorted by historical revisionism',
  'A scenario where the concept of truth is not obscured by propaganda',
  'A world where the fabric of reality is not threatened by nuclear war',
  'A situation where the laws of causality are not ignored by the powerful',
  'A realm where the power of creativity is not stifled by censorship',
  'A fire station catching on fire',
  "A character named 'Lucky' experiencing a string of bad luck",
  "A politician named 'Honesty' embroiled in a corruption scandal",
  'A group of pacifists starting a violent revolution',
  "A person named 'Hope' struggling with depression",
  "A 'Save the Planet' conference held in a pollution-filled auditorium",
  "A 'Unity' rally ending in chaos and division",
  "A 'Truth' serum causing people to tell lies",
  "A 'Peace' treaty leading to a devastating war",
  "A 'Freedom' fighter becoming a dictator",
  "A 'Love' potion causing hatred and anger",
  "A 'Happiness' pill leading to depression and sadness",
  "A 'Knowledge' book containing false information",
  "A 'Wisdom' guru making foolish decisions",
  "A 'Courage' medal awarded to a coward",
  "A 'Justice' system perpetuating inequality",
  "A 'Equality' movement marginalizing minority groups",
  "A 'Free Speech' zone where opinions are censored",
  "A 'Democracy' where the government ignores the people",
  "A 'Progress' conference where no progress is made",
  "A 'Innovation' award given to a copycat",
  "A 'Creativity' class taught by a unoriginal teacher",
  "A 'Success' story ending in failure",
  "A 'Dream' vacation turning into a nightmare",
  "A 'Perfect' relationship filled with flaws",
  "A 'Utopia' society with hidden dark secrets",
  'A character discovering their memories are false',
  'A person being stalked by their own doppelganger',
  'A group of friends trapped in a never-ending time loop',
  'A person waking up with no identity or past',
  'A character haunted by a manifestation of their own guilt',
  'A person slowly losing their grip on reality',
  'A group of strangers trapped in a room with no escape',
  "A character's sanity unravelling due to isolation",
  "A person's darkest fears taking physical form",
  "A character's past mistakes coming back to haunt them",
  "A person's own reflection turning against them",
  'A character trapped in a world of their own delusions',
  "A person's sense of identity slowly disintegrating",
  "A character's memories being manipulated and altered",
  "A person's perception of reality slowly warping",
  "A character's inner demons manifesting in the physical world",
  "A person's own voice whispering cruel truths in their ear",
  "A character's grip on reality faltering due to paranoia",
  "A person's own shadow turning against them",
  "A character's darkest thoughts taking on a life of their own",
  "A person's own face staring back at them with malevolent intent",
  "A character's sense of self disintegrating due to trauma",
  "A person's own mind working against them",
  "A character's memories being stolen and replaced with false ones",
  "A person's own reflection showing them their darkest fears",
  "A character's inner turmoil manifesting as a physical presence",
  "A person's own voice screaming cruel truths in their ear",
  'A world where dreams are a parallel reality',
  'A society where magic is a part of everyday life',
  'A realm where mythical creatures are real',
  'A dimension where time has no meaning',
  'A place where the skies are painted with colors that change with the seasons',
  'A land where the trees whisper secrets to those who listen',
  'A kingdom ruled by a wise and just dragon',
  'A world where memories can be transferred from one person to another',
  'A realm where the elements are in constant flux',
  'A place where the stars are within reach',
  'A society where the concept of money is obsolete',
  'A dimension where the laws of physics are flexible',
  'A world where the creatures of myth and legend roam free',
  'A place where the fabric of reality is woven with magic',
  'A realm where the cycles of life and death are intertwined',
  'A land where the wind whispers ancient secrets',
  'A kingdom where the sun never sets',
  'A world where the concept of time is fluid',
  'A realm where the elements are in harmony',
  'A place where the skies are filled with wonders',
  'A society where the art of magic is revered',
  'A dimension where the impossible becomes possible',
  'A world where the creatures of fantasy roam free',
  'A place where the fabric of reality is ever-changing',
  'A realm where the cycles of life and death are ever-turning',
  'A prophecy foretelling the arrival of a powerful sorceress',
  'A quest to retrieve a legendary sword from a treacherous realm',
  'A rebellion against a tyrannical sorcerer-king',
  'A discovery of a hidden city deep in a mystical forest',
  'A battle between good and evil for control of a magical artifact',
  'A journey to unite warring factions against a common enemy',
  'A search for a powerful magical crystal hidden across realms',
  'A confrontation with a dragon guarding a treasure trove',
  'A race against time to prevent a catastrophic magical event',
  'A quest to prove oneself worthy of wielding a legendary weapon',
  'A struggle to maintain balance between light and darkness',
  "A mission to infiltrate an enemy's stronghold and steal a powerful spellbook",
  'A battle to protect a magical realm from invasion',
  'A search for a lost tribe with ancient magical knowledge',
  'A confrontation with a powerful demon summoned by a rival sorcerer',
  'A journey to uncover the secrets of a mysterious magical ruin',
  'A quest to unite the fragments of a shattered magical artifact',
  'A struggle to resist the temptation of dark magic',
  'A mission to escort a powerful magical being to a sacred site',
  'A battle to defend a magical kingdom from a siege',
  'A search for a magical cure for a deadly curse',
  "A confrontation with a traitor within one's own ranks",
  'A journey to explore a newly discovered magical realm',
  'A quest to master a powerful magical ability',
  'A struggle to maintain peace in a realm of conflicting magical interests',
  'A discovery of an ancient alien artifact with secrets of the universe',
  'A mission to colonize a new planet with limited resources',
  'A rebellion against an oppressive AI regime',
  'A quest to prevent a catastrophic asteroid impact',
  'A journey through a wormhole to an unknown dimension',
  'A battle against an alien invasion force',
  'A search for a lost generation ship with valuable technology',
  'A confrontation with a rogue AI entity',
  'A race against time to prevent a deadly pandemic from spreading',
  'A mission to explore a mysterious derelict spacecraft',
  'A struggle to survive on a hostile alien environment',
  'A quest to uncover the truth about a sinister government agency',
  'A journey to the edge of the universe to discover its secrets',
  'A battle to protect humanity from an alien threat',
  'A search for a new source of energy to save a dying planet',
  'A confrontation with a rival scientist with a hidden agenda',
  'A mission to terraform a hostile planet for human habitation',
  'A quest to prevent a catastrophic cosmic event',
  'A journey through time to prevent a disaster',
  'A struggle to maintain humanity in a world of advanced technology',
  'A mission to explore a mysterious black hole',
  'A battle against an alien entity that can manipulate reality',
  'A search for a lost civilization with advanced technology',
  'A confrontation with a powerful alien warlord',
  'A journey to the center of the galaxy to discover its secrets',
  'A detective investigating a murder with no leads or evidence',
  'A mysterious disappearance in a small town with a dark secret',
  'A theft of a priceless artifact with no signs of forced entry',
  'A murder victim with no identity or known connections',
  'A mysterious letter with no return address or clear message',
  'A detective with a personal connection to the case',
  'A suspect with a solid alibi but questionable motives',
  'A mysterious figure lurking in the shadows',
  'A cryptic message or code to decipher',
  "A detective's trusted partner accused of the crime",
  'A crime scene with no signs of struggle or forced entry',
  'A mysterious stranger in town with unknown intentions',
  "A detective's own dark past connected to the case",
  'A case with no motive or apparent connection between victims',
  'A mysterious organization or society involved in the crime',
  'A detective racing against time to prevent another crime',
  'A case with a surprising twist or unexpected culprit',
  "A detective's own life threatened by the perpetrator",
  'A mysterious inheritance or will with hidden meanings',
  'A detective uncovering a web of deceit and lies',
  'A case involving a mysterious artifact or relic',
  "A detective's trusted informant with questionable loyalty",
  'A mysterious event or occurrence with no explanation',
  "A detective's own judgment clouded by personal bias",
  'A case with a mysterious or unknown perpetrator',
  'A detective uncovering a dark conspiracy or cover-up',
  "A young soldier's journey during World War I",
  "A family's struggle to survive during the Great Depression",
  "A spy's mission during the Cold War",
  'A royal court intrigue in ancient Egypt',
  "A warrior's quest during the Crusades",
  "A pioneer's journey across the American West",
  "A slave's fight for freedom during the Civil War",
  "A knight's honor tested during the Middle Ages",
  "A pharaoh's rise to power in ancient Egypt",
  "A Viking's raid on a foreign land",
  "A samurai's loyalty tested in feudal Japan",
  "A young queen's ascension to the throne",
  "A peasant's revolt against a corrupt government",
  "A conquistador's quest for gold and glory",
  "A sailor's journey on the high seas during the Age of Exploration",
  "A noble's struggle to maintain power during a time of war",
  "A commoner's rise to wealth and influence",
  "A priest's crisis of faith during the Inquisition",
  "A warrior's redemption after a great battle",
  "A courtier's intrigue in the palace of a powerful monarch",
  "A merchant's journey along the Silk Road",
  "A monk's quest for knowledge during the Dark Ages",
  "A rebel's fight against an oppressive government",
  "A general's strategic battle plan during a war",
  "A spy's deception and betrayal during a time of war",
  "A leader's difficult decision during a time of crisis",
  'A chance encounter between two strangers on a train',
  'A friends-to-lovers story with a twist',
  'A second chance at love after a painful past',
  'A forbidden love between two people from different worlds',
  'A love triangle with a surprising twist',
  'A romance that blossoms during a road trip',
  'A secret admirer with a hidden identity',
  'A love story set in a small town with a strong sense of community',
  'A couple reuniting after years apart',
  'A fake relationship that turns into real feelings',
  'A love story set against the backdrop of a music festival',
  'A romance that develops through letters or emails',
  'A couple navigating a long-distance relationship',
  'A love story set in a picturesque coastal town',
  'A secret love affair with a coworker',
  'A romance that blooms during a family gathering',
  'A love story set in a vibrant city with a diverse cast of characters',
  'A couple overcoming a traumatic event together',
  'A love story told through a series of flashbacks',
  'A romance that develops between two people from different cultures',
  'A love story set in a beautiful vineyard or winery',
  'A couple rekindling their spark after a rough patch',
  'A love story set during a holiday or special occasion',
  'A romance that develops between two people with different personalities',
  'A love story set in a quaint bookshop or library',
  'A couple navigating the challenges of a blended family',
  "A character's daily commute to work",
  'A trip to the grocery store',
  'Doing laundry and folding clothes',
  'Cooking a simple meal',
  'Cleaning the house',
  'Running errands',
  'A boring meeting at work',
  "A character's morning routine",
  'Taking out the trash and recycling',
  'Paying bills and managing finances',
  "A character's daily walk or jog",
  'Shopping for new clothes',
  'Attending a family gathering',
  "A character's favorite hobby or activity",
  'A trip to the bank',
  "A character's daily coffee or tea routine",
  'A trip to the post office',
  "A character's favorite TV show or movie",
  'A trip to the library',
  "A character's daily reading routine",
  'A trip to the gym',
  "A character's favorite food or restaurant",
  'A trip to the park',
  "A character's daily work routine",
  'A trip to the dentist',
  "A character's favorite music or artist",
  'A trip to the hair salon',
  "A character's daily phone or computer routine",
  'A trip to the gas station',
  "A character's favorite book or author",
  "A character's ridiculous attempt to cook a meal",
  'A silly misunderstanding with a neighbor',
  'A hilarious mishap at the gym',
  "A character's disastrous first date",
  'A ridiculous fashion choice or wardrobe malfunction',
  'A silly argument with a friend or family member',
  "A character's failed attempt at a new hobby",
  'A humorous encounter with a pesky pet',
  'A silly mistake at work or school',
  "A character's ridiculous obsession with a TV show or movie",
  'A silly misunderstanding with a stranger',
  "A character's hilarious reaction to a scary situation",
  'A silly prank gone wrong',
  "A character's ridiculous attempt to impress someone",
  'A silly misadventure on a road trip',
  "A character's hilarious encounter with a weird food",
  'A silly mistake with a DIY project',
  "A character's ridiculous fear or phobia",
  'A silly encounter with a quirky coworker or classmate',
  "A character's hilarious attempt to learn a new skill",
  'A silly misunderstanding with a technology device',
  "A character's ridiculous superstition or ritual",
  'A silly encounter with a eccentric family member',
  "A character's hilarious reaction to a surprise party",
  'A silly mistake with a gift or present',
  'A high-speed car chase through a crowded city',
  'A intense hand-to-hand combat scene',
  'A mission to infiltrate a heavily guarded facility',
  'A battle against a powerful and ruthless enemy',
  'A race against time to defuse a bomb',
  'A daring escape from a dangerous situation',
  'A showdown with a rival or arch-nemesis',
  'A mission to retrieve a valuable and dangerous artifact',
  'A fight to protect a loved one or innocent bystander',
  'A high-stakes heist or robbery',
  'A battle to take down a criminal organization',
  'A mission to rescue a hostage or kidnapped victim',
  'A intense gunfight or shootout',
  'A chase through a treacherous terrain or landscape',
  'A battle against a formidable and skilled opponent',
  'A mission to stop a catastrophic event or disaster',
  "A fight to clear one's name or reputation",
  'A showdown with a powerful and corrupt authority figure',
  'A mission to uncover a conspiracy or cover-up',
  'A battle to save the world from a deadly threat',
  'A intense and dangerous infiltration mission',
  'A fight to protect a valuable resource or asset',
  'A mission to take down a dangerous and elusive target',
  'A battle to survive in a hostile environment',
  'A showdown with a rival or enemy in a final confrontation',
  'Discovering a hidden treasure map',
  'Embarking on a perilous journey to a mysterious island',
  'Uncovering a ancient secret or lost civilization',
  'Exploring a long-abandoned temple or ruin',
  'Setting sail on a high-seas adventure',
  'Venturing into a dense and uncharted jungle',
  'Climbing a treacherous mountain or peak',
  'Navigating a treacherous desert or wasteland',
  'Discovering a hidden underwater city or treasure',
  'Embarking on a quest to find a legendary artifact',
  'Exploring a mysterious and unexplained phenomenon',
  'Journeying to a strange and exotic land',
  'Uncovering a conspiracy or hidden plot',
  'Setting out on a solo adventure with no clear destination',
  'Discovering a hidden talent or skill',
  'Embarking on a journey to find a lost loved one',
  'Exploring a mysterious and abandoned mine or cave',
  'Venturing into a strange and uncharted forest',
  'Climbing a towering and treacherous waterfall',
  'Discovering a hidden world or dimension',
  'Embarking on a quest to save a kingdom or people',
  'Exploring a mysterious and ancient tomb',
  'Setting sail on a pirate adventure',
  'Journeying to a mysterious and isolated monastery',
  'Uncovering a hidden prophecy or destiny',
  'Embarking on a journey to find a legendary creature',
  'Waking up in a strange and terrifying place',
  "Discovering a dark secret in your family's past",
  'Being stalked by a supernatural entity',
  'Uncovering a sinister plot in a small town',
  'Exploring a haunted mansion or asylum',
  'Surviving a night in a creepy campground',
  'Encountering a terrifying creature in the woods',
  'Being trapped in a never-ending nightmare',
  'Discovering a cursed object or artifact',
  'Uncovering a dark conspiracy involving a cult',
  'Escaping a zombie apocalypse',
  'Surviving a demonic possession',
  'Exploring a haunted hospital or morgue',
  'Encountering a malevolent spirit or ghost',
  'Being trapped in a time loop of terror',
  'Uncovering a sinister plot involving a government agency',
  'Surviving a slasher or serial killer',
  'Discovering a terrifying secret in your own reflection',
  "Uncovering a dark secret in a friend or loved one's past",
  'Exploring a haunted cemetery or graveyard',
  'Encountering a terrifying creature from folklore or legend',
  'Being trapped in a never-ending cycle of terror',
  'Uncovering a sinister plot involving a supernatural force',
  'Surviving a terrifying encounter with a monster or creature',
  'A high school student discovers a hidden power',
  'A group of friends form a team to battle against an evil organization',
  'A young protagonist is transported to a fantasy world',
  'A hero must choose between their duty and their heart',
  'A group of students must work together to survive a deadly tournament',
  'A protagonist discovers a mysterious artifact with great power',
  'A hero must confront their dark past to save the future',
  'A group of friends must band together to defeat a powerful demon',
  'A protagonist is reborn into a new world with a second chance',
  'A hero must navigate a complex web of alliances and rivalries',
  'A group of students must uncover the truth behind a mysterious event',
  'A protagonist discovers a hidden world within their own reflection',
  'A hero must make a difficult choice to save the ones they love',
  'A group of friends must escape a deadly trap or puzzle',
  'A protagonist is given a powerful weapon with a great cost',
  'A hero must confront their own doubts and fears to succeed',
  'A group of students must work together to defeat a powerful foe',
  "A protagonist discovers a hidden truth about their family's past",
  'A hero must navigate a complex moral dilemma',
  'A group of friends must survive a deadly adventure or quest',
  'A protagonist is given a second chance at life with a new power',
];
const roundThreePrompts = [
  "Cinderella's Glass Slipper",
  "Snow White's Poison Apple",
  "Sleeping Beauty's Dream Pillow",
  "Beauty and the Beast's Enchanted Rose",
  "Rapunzel's Hair-Raising Adventure",
  "Hansel and Gretel's Gingerbread House",
  "Little Mermaid's Seashell Phone",
  "Jack and the Beanstalk's Magic Beans",
  "Goldilocks' Porridge",
  "Rumplestiltskin's Spinning Wheel",
  "The Frog Prince's Leap",
  "Puss in Boots' Purrfect Shoes",
  "Red Riding Hood's Hoodie",
  "The Three Little Pigs' Eco-Friendly Homes",
  "Aladdin's Magic Carpet Ride",
  "The Ugly Duckling's Feathered Friends",
  "The Emperor's New Clothes",
  "The Twelve Dancing Princesses' Shoes",
  "The Boy Who Cried Wolf's Sustainable Farm",
  "The Gingerbread Man's Sweet Treats",
  "The Three Billy Goats Gruff's Bridge",
  "The Little Mermaid's Seaside Sanctuary",
  "Cinderella's Pumpkin Coach",
  "Snow White's Apple a Day",
  "Sleeping Beauty's Dreamy Bedding",
  "Beauty and the Beast's Enchanted Garden",
  "Rapunzel's Hair-Raising Haircare",
  "Hansel and Gretel's Gingerbread House 2.0",
  "Little Red Riding Hood's Hoodie 2.0",
  "The Frog Prince's Leap of Faith",
  "Puss in Boots' Purrfectly Sustainable",
  "The Three Little Pigs' Eco-Friendly Homes 2.0",
  "Aladdin's Magic Carpet Ride 2.0",
  "The Princess and the Pea's Perfect Pillow",
  "The Steadfast Tin Soldier's Sustainable Armor",
  "The Snow Queen's Icy Innovations",
  "The Velveteen Rabbit's Cuddle Cure",
  "The Elves and the Shoemaker's Sustainable Shoes",
  "The Town Mouse and the Country Mouse's Eco-Friendly Abode",
  "Dragon's Hoard Heist",
  'Fire-Breathing Startup',
  'Scale-Tastic Fashion',
  "Dragon Rider's Quest",
  'Treasure Trove Discovery',
  'Blazing Inferno Rescue',
  "Dragon's Den Pitch",
  'Mythical Creature Encounter',
  'Fiery Flight School',
  'Ancient Dragon Prophecy',
  "Treacherous Dragon's Lair",
  "Dragon's Breath Coffee",
  'Legendary Dragon Sighting',
  "Dragon's Gold Rush",
  'Scaly Skin Solutions',
  "Dragon's Eye View",
  'Inferno Insurance Agency',
  "Dragon's Fury Workout",
  "Treasure Hunter's Guide",
  "Dragon's Roar Recording",
  "Blazing Dragon's Path",
  "Dragon's Claw Security",
  'Fiery Passion Project',
  "Dragon's Den Defense",
  'Mythical Dragon Rider',
  "Treacherous Dragon's Peak",
  "Dragon's Hoard Investment",
  'Legendary Dragon Slayer',
  "Dragon's Breath BBQ",
  'Scaly Skin Care',
  "Dragon's Eye Spy",
  'Inferno Innovations',
  "Dragon's Fury Fitness",
  "Treasure Hunter's Quest",
  "Dragon's Roar Revolution",
  "Blazing Dragon's Trail",
  "Dragon's Claw Consulting",
  "Fiery Dragon's Soul",
  "Dragon's Den Dynamics",
  'Zombie Apocalypse Survival Guide',
  'Undead Coding Challenge',
  'Brain-Hungry Startup',
  'Zombie-Themed Food Truck',
  "Necromancer's Apprentice",
  'Zombie-Proof Shelter Design',
  'Flesh-Eating Fashion Disaster',
  'Zombie Outbreak Response Team',
  'Reanimated Research Project',
  'Zombie-Inspired Workout Routine',
  'Cemetery Security Breach',
  'Zombie Apocalypse Insurance Policy',
  "Grave Digger's Dilemma",
  'Zombie-Fighting Drone Development',
  'Apocalypse Preparedness Kit',
  'Zombie-Themed Amusement Park',
  'Undead Social Media Platform',
  'Zombie-Infested Virtual Reality',
  'Necromancy for Beginners',
  'Zombie-Proof Vehicle Design',
  'Flesh-Eating Fungus Research',
  'Zombie Outbreak Investigation Team',
  'Reanimated Robotics Lab',
  'Zombie-Inspired Art Studio',
  'Cemetery Restoration Project',
  'Zombie Apocalypse Survival Kit',
  "Grave Robber's Revenge",
  'Zombie-Fighting Exosuit Development',
  'Apocalypse Survival Guide',
  'Zombie-Themed Coffee Shop',
  'Undead Talent Agency',
  'Zombie-Infested Video Game',
  'Necromancy for Experts',
  'Zombie-Proof Home Security',
  'Flesh-Eating Bacteria Research',
  'Zombie Outbreak Response Protocol',
  'Reanimated Research Facility',
  'Zombie-Inspired Music Festival',
  'Cemetery Expansion Project',
  'Zombie Apocalypse Prevention Plan',
  "Galactic Ambassador's Quandary",
  'Alien Invasion Survival',
  'Intergalactic Trade Negotiations',
  'Cosmic Expedition Disaster',
  'Extraterrestrial Life Discovery',
  'Space Station Crisis',
  'Alien Artifact Analysis',
  'Planetary Colonization Challenge',
  'Interstellar War Treaty',
  'Alien Abduction Enigma',
  "Galactic Explorer's Journey",
  'Alien Technology Reverse-Engineering',
  'Cosmic Phenomenon Investigation',
  'Spacecraft Malfunction',
  'Alien Diplomacy Dilemma',
  'Intergalactic Smuggling Ring',
  'Planetary Defense System',
  'Alien Hybrid Experiment',
  'Galactic Governance Crisis',
  'Cosmic Anomaly Detection',
  'Alien Language Deciphering',
  'Space Colony Uprising',
  'Alien Artifact Recovery',
  'Galactic Exploration Initiative',
  'Cosmic Storm Survival',
  'Alien Encounter Protocol',
  'Intergalactic Espionage Mission',
  'Planetary Terraforming Project',
  'Alien Technology Theft',
  'Galactic Peace Treaty',
  'Cosmic Entity Encounter',
  'Alien Abduction Rescue',
  'Space Station Rebellion',
  'Alien Lifeform Discovery',
  'Galactic Expedition Leader',
  'Cosmic Event Horizon',
  'Alien Invasion Defense',
  'Tsunami Warning Failure',
  'Pandemic Outbreak Response',
  'Hurricane Evacuation Crisis',
  'Wildfire Inferno',
  'Earthquake Rescue Mission',
  'Volcanic Eruption Evacuation',
  'Flood Disaster Relief',
  'Drought Emergency Response',
  'Heatwave Health Crisis',
  'Blizzard Survival Story',
  'Landslide Rescue Operation',
  'Tornado Alley Destruction',
  'Cyclone Devastation',
  'Solar Flare Catastrophe',
  'Meteor Impact Scenario',
  'Global Power Grid Failure',
  'Economic Collapse Consequences',
  'Environmental Catastrophe',
  'Nuclear Meltdown Aftermath',
  'Biological Warfare Outbreak',
  'Cyber Attack Crisis',
  'Food Shortage Emergency',
  'Water Scarcity Disaster',
  'Climate Change Cataclysm',
  'Geological Upheaval',
  'Marine Disaster Response',
  'Avalanche Rescue Mission',
  'Radioactive Spill Cleanup',
  'Toxic Gas Leak Evacuation',
  'Magnetic Pole Reversal',
  'Supervolcanic Eruption',
  'Gamma Ray Burst Aftermath',
  'Robot Uprising Crisis',
  'Artificial Intelligence Takeover',
  'Zombie Apocalypse Scenario',
  'Alien Invasion Disaster',
  'Totalitarian Regime Uprising',
  'Surveillance State Rebellion',
  'Climate Catastrophe Aftermath',
  'Corporate Oligarchy Overthrow',
  'Government Corruption Exposé',
  'Technological Singularity Crisis',
  'Social Hierarchy Revolution',
  'Economic Inequality Uprising',
  'Biometric Control Resistance',
  'Artificial Intelligence Dictatorship',
  'Virtual Reality Dystopia',
  'Cyberpunk Uprising',
  'Nuclear War Survival',
  'Pandemic Dystopia',
  'Total Surveillance Society',
  'Government Experiment Gone Wrong',
  'Corporate Conspiracy Uncovered',
  'Climate Engineering Disaster',
  'Social Credit System Rebellion',
  'Autonomous Weapon Ethics Crisis',
  'Neurotechnology Control',
  'Dystopian Propaganda Machine',
  'Rebel Alliance Formation',
  'Underground Resistance Movement',
  'Dystopian City-State Uprising',
  'AI-Powered Dictatorship',
  'Virtual Reality Revolution',
  'Cyber Warfare Crisis',
  'Nanotechnology Disaster',
  'Transhumanism Ethics Debate',
  'Surveillance Capitalism Collapse',
  'Biotechnology Dystopia',
  'Climate Change Denial Consequences',
  'Government Brainwashing Program',
  'Corporate Whistleblower Protection',
  'Social Hierarchy Reform',
  'Economic Democracy Experiment',
  "Airship Pirate's Plunder",
  'Clockwork Revolution',
  'Steam-Powered Uprising',
  'Gearhive Metropolis',
  'Aetherium Mining Expedition',
  'Copperplate Conspiracy',
  'Brass Automaton Rebellion',
  'Steam Engine Heist',
  "Clockworker's Guild War",
  "Aerostat Pirates' Lair",
  'Gearbox Innovation',
  'Steam-Powered Mecha',
  'Aetherium Smuggling Ring',
  'Clockwork Creature Creation',
  'Copperplate Cipher',
  'Brass Behemoth Rampage',
  'Steam Engine Breakthrough',
  "Clockworker's Apprentice",
  'Aerostat Expedition',
  'Gearhive Politics',
  'Steam-Powered Transportation',
  'Aetherium Discovery',
  'Clockwork Invention Convention',
  'Copperplate Forgery',
  'Brass Golem Uprising',
  'Steam Engine Malfunction',
  "Clockworker's Dilemma",
  'Aerostat Disaster',
  'Gearbox Mystery',
  'Steam-Powered Exploration',
  'Aetherium Trade Wars',
  'Clockwork Soldier Rebellion',
  'Copperplate Decryption',
  'Brass Dragon Rampage',
  'Steam Engine Innovation',
  "Clockworker's Legacy",
  'Mysterious Portal Discovery',
  "Interdimensional Traveler's Quest",
  'Fantastical World Exploration',
  'Magical Gateway Encounter',
  'Alternate Reality Convergence',
  'Mythical Creature Alliance',
  'Hidden Portal Protection',
  'Cross-Dimensional Romance',
  'Portal Key Quest',
  'Fantasy Realm Rebellion',
  'Interdimensional War Outbreak',
  'Mystical Portal Guardian',
  'Alternate Dimension Survival',
  'Fantastical Creature Encounter',
  'Portal Magic Mastery',
  'Interdimensional Politics',
  'Fantasy World Revolution',
  'Hidden Gateway Discovery',
  'Cross-Dimensional Friendship',
  'Portal Prophecy Unveiled',
  'Fantastical Quest Completion',
  'Interdimensional Exploration Team',
  'Mystical Realm Expedition',
  'Alternate Reality Conundrum',
  'Fantasy Creature Diplomacy',
  'Portal Technology Development',
  'Interdimensional Detective Work',
  'Fantastical World-Building',
  'Hidden Portal Conspiracy',
  'Cross-Dimensional Deception',
  'Portal Guardian Legacy',
  'Fantasy Realm Unity',
  'Interdimensional Odyssey',
  'Mystical Gateway Adventure',
  'Forced Marriage Scenario',
  'Love Triangle Dilemma',
  'Family Business Power Struggle',
  'Friendship Betrayal Consequences',
  'Hidden Identity Revelation',
  'Social Class Difference Conflict',
  'Office Romance Complications',
  'Family Secret Exposure',
  'Rivalry Turned Romance',
  'Tragic Past Revelation',
  'Friendship Goals Achievement',
  'Love Confession Consequences',
  'Career vs. Relationship Dilemma',
  'Family Reunion Drama',
  'Hidden Talent Discovery',
  'Social Status Pressure',
  'Unrequited Love Struggles',
  'Friendship Turned Rivalry',
  'Family Legacy Burden',
  'Love Square Complications',
  'Past Trauma Overcoming',
  'Friendship Loyalty Test',
  'Social Hierarchy Challenge',
  'Hidden Agenda Exposure',
  'Love vs. Duty Conflict',
  'Family Honor Protection',
  'Rivalry Resolution',
  'Tragic Ending Redemption',
  'Friendship Forgiveness',
  'Social Norm Defiance',
  'Unconditional Love Demonstration',
  'Family Unity Restoration',
  'Love Triumph Over Adversity',
  "Abandoned Toy's Lonely Journey",
  "Vintage Clock's Ticking Memories",
  "Forgotten Book's Hidden Knowledge",
  "Lost Key's Quest for Purpose",
  "Old Chair's Comforting Stories",
  "Traveling Suitcase's Adventures",
  "Piano's Melodic Memories",
  "Painting's Colorful History",
  "Antique Vase's Fragile Beauty",
  "Worn-Out Shoe's Tireless Journey",
  "Family Heirloom's Legacy",
  "Broken Toy's Repair Journey",
  "Vintage Camera's Focal Memories",
  "Forgotten Photograph's Hidden Story",
  "Old Guitar's Melodic Past",
  "Lost Diary's Secret Keepers",
  "Timeless Watch's Enduring Time",
  "Weathered Umbrella's Stormy Days",
  "Pillow's Soft Whispers",
  "Vintage Typewriter's Written Tales",
  "Paintbrush's Artistic Expressions",
  "Old Map's Mysterious Routes",
  "Forgotten Recipe's Culinary Secrets",
  "Vintage Radio's Tuned Memories",
  "Worn-Out Book's Dog-Eared Pages",
  "Antique Door's Creaky Hinges",
  "Family Recipe's Treasured Ingredients",
  "Old Compass's Guiding Directions",
  "Vintage Bicycle's Wheels of Freedom",
  'Ancient Tome Discovery',
  'Creepy Mansion Inheritance',
  'Mysterious Cult Encounter',
  'Eldritch Horror Summoning',
  'Sanity-Blurring Vision',
  'Forbidden Knowledge Quest',
  'Cthulhu Worshipper Confrontation',
  'Otherworldly Dream Invasion',
  'Unsettling Artifact Acquisition',
  "Old Gods' Whispers",
  'Cosmic Horror Revelation',
  'Mysterious Disappearance Investigation',
  'Eerie Island Isolation',
  'Unholy Ritual Interruption',
  'Mind-Bending Dimensional Shift',
  'Grotesque Creature Confrontation',
  'Ancient Deity Resurrection',
  'Unnerving Shadow Presence',
  'Forbidding Forest Expedition',
  'Unraveling Sanity',
  'Cursed Relic Possession',
  'Eerie Whispers in the Dark',
  'Unholy Alliance Formation',
  'Apocalyptic Prophecy Unveiling',
  'Unsettling Time Loop',
  'Otherworldly Entity Communication',
  'Unnerving Reality Distortion',
  'Creepy Doll Possession',
  'Mysterious Portrait Enigma',
  'Unholy Transformation',
  'Ancient Temple Desecration',
  'Unnerving Silence',
  'Eldritch Power Struggle',
  'Neon-Lit Cityscape Exploration',
  'Corporate Conspiracy Unveiling',
  'Virtual Reality Uprising',
  'Cybernetic Enhancement Dilemma',
  'Hacking Crew Recruitment',
  'Artificial Intelligence Rebellion',
  'Shadowy Underground Organization',
  'Biomechanical Upgrade Experimentation',
  'Dystopian Future Rebellion',
  'Virtual Identity Crisis',
  'Steampunk Airship Heist',
  'Cyberpunk Bar Brawl',
  "Neuromancer's Virtual Quest",
  'Synthetic Human Rights Activism',
  'Cyberwarfare Espionage',
  'Ghost in the Shell-Inspired Hacking',
  'Blade Runner-Style Replicant Hunt',
  'Matrix-Like Reality Distortion',
  'Rogue AI Confrontation',
  'Cyberpunk Motorcycle Gang Encounter',
  'High-Tech Surveillance State Subversion',
  'Underground Club Clandestine Meeting',
  'Neon-Drenched City Streets Survival',
  'Corporate Security Infiltration',
  'Cyber-Enhanced Mercenary Mission',
  'Virtual Reality Addiction Recovery',
  'Dystopian Government Resistance',
  'Bio-Mechanical Implant Experimentation',
  'Cyberpunk-Style Fashion Show',
  'Hacking Tournament Competition',
  'Virtual Reality World Creation',
  'Cyberpunk-Themed Arcade Game Development',
  'Ancient Egyptian Pyramid Expedition',
  'Medieval Castle Siege Survival',
  'Future Space Station Crisis',
  'Dinosaur Era Adventure',
  'Wild West Outlaw Encounter',
  'Roaring Twenties Speakeasy Caper',
  'Ancient Greek Olympic Games Participation',
  'Futuristic City-State Politics',
  'Prehistoric Mammooth Hunting',
  'Renaissance Art Studio Visit',
  'Time-Loop Paradox Resolution',
  'Historical Figure Meeting',
  'Steampunk Airship Voyage',
  'Jurassic Park-Style Dinosaur Encounter',
  'Viking Raid Survival',
  'Clockwork Machine Time-Travel',
  'Ancient Mayan Temple Exploration',
  'Future Robot Uprising',
  "Pirate's Caribbean Plunder",
  'Ancient Chinese Dynasty Intrigue',
  'Time-Traveling Car Chase',
  "Egyptian Pharaoh's Court Intrigue",
  'Futuristic Space Exploration',
  "Medieval Knight's Quest",
  'Prehistoric Tribe Encounter',
  'Ancient Roman Colosseum Games',
  'Time-Traveling Love Story',
  'Futuristic Cyberpunk City',
  'Ancient Greek Mythology Adventure',
  'Time-Loop Conspiracy Unraveling',
  'Historical Event Alteration',
  'Echoes of Memories Past',
  'Fractured Reality Repair',
  'Whispers in the Void',
  'Shattered Dreams Reconstruction',
  'Infinity Loop Conundrum',
  'Parallel Universe Convergence',
  'Timeless Dilemma Resolution',
  'Cosmic Balance Restoration',
  'Ephemeral Existence Crisis',
  'Multiverse Exploration',
  'Paradoxical Choice',
  'Quantum Flux Navigation',
  'Reality Distortion Field',
  'Surreal Landscape Survival',
  'Thought Experiment Gone Wrong',
  'Unraveling the Fabric of Reality',
  'Abstract Expressionism Adventure',
  'Causality Chain Reaction',
  'Dreamscape Odyssey',
  'Echo Chamber of the Mind',
  'Fractured Identity Reintegration',
  'Gravity Well Conundrum',
  'Hyperspace Travel Dilemma',
  'Infinite Corridor Puzzle',
  'Kaleidoscope of Possibilities',
  'Labyrinth of Reflections',
  'Mind Maze Escape',
  'Nexus of Parallel Worlds',
  'Ontological Crisis Resolution',
  'Paradoxical Unity',
  'Quantum Consciousness Exploration',
  'Moonlit Garden of Dreams',
  'Whispers in the Wind',
  'Forgotten Memories Revival',
  'Echoes of Love Lost',
  'River of Thoughts Meandering',
  'Starlight Serenade Performance',
  'Rainy Day Reflections',
  'Wildflower Meadow Wander',
  'Sunset Sky Poetry Inspiration',
  'Morning Dew Droplet Wisdom',
  'Forgotten Library Book Discovery',
  'Vintage Typewriter Poem Composition',
  'Candlelit Room Confessions',
  'Snowflake Gentlefall',
  'Ocean Waves Melody',
  'Forgotten Photograph Memories',
  'Vintage Postcard Storytelling',
  'Lullaby of Lost Souls',
  "Forgotten Lovers' Letters",
  'Moonbeam Whispers Secrets',
  'Riverbank Soliloquy',
  'Sunrise Hope Revival',
  'Midnight Sky Contemplation',
  'Forgotten Childhood Memories',
  'Whispering Walls Secrets',
  'Rainy Night Jazz Improvisation',
  'Forgotten Bookshelf Treasures',
  'Vintage Camera Snapshot Moments',
  'Lullaby of Forgotten Dreams',
  'Forgotten Garden Blooming',
  'Moonlight Sonata Performance',
  'Investigating a Real-Life Mystery',
  'Documenting a Historical Event',
  'Solving a Scientific Enigma',
  'Uncovering a Hidden Truth',
  'Exploring a Natural Wonder',
  'Surviving a Natural Disaster',
  'Participating in a Social Movement',
  'Conducting a Journalism Investigation',
  'Writing a Memoir Chapter',
  'Conquering a Personal Challenge',
  'Overcoming a Phobia',
  'Learning a New Skill',
  'Traveling to a Foreign Country',
  'Attending a Historic Event',
  'Meeting an Inspiring Figure',
  'Volunteering for a Good Cause',
  'Starting a New Business Venture',
  'Running a Marathon',
  'Climbing a Mountain',
  'Learning a New Language',
  'Cooking a New Cuisine',
  'Starting a Journaling Practice',
  'Conducting an Experiment',
  'Solving a Real-World Problem',
  'Creating a Community Project',
  'Writing a Letter to the Editor',
  'Giving a Public Speech',
  'Participating in a Debate',
  'Leading a Team Project',
  'Mentoring Someone',
  'Learning from Failure',
  'Developing a New Habit',
  'Childhood Memory Revival',
  'First Love Story Retelling',
  'Overcoming a Personal Fear',
  'Family Tradition Exploration',
  'Cultural Heritage Discovery',
  'Personal Growth Milestone',
  'Challenging Life Decision',
  'Travel Experience Reflection',
  'Lessons Learned from Failure',
  'Memorable Teacher Influence',
  'Formative Friendship Experience',
  'Family Member Tribute',
  'Personal Achievement Celebration',
  'Life-Changing Book Inspiration',
  'Role Model Encounter',
  'Personal Values Reflection',
  "Life's Most Important Lesson",
  'Pivotal Career Choice',
  'Personal Identity Exploration',
  'Coping with Adversity',
  "Life's Biggest Risk",
  'Most Influential Place',
  'Childhood Dream Realization',
  'Personal Hero Story',
  "Life's Hardest Goodbye",
  'Personal Freedom Moment',
  'Most Impactful Experience',
  'Personal Legacy Hope',
  "Life's Most Important Relationship",
  'Personal Resilience Story',
  "Life's Biggest Accomplishment",
  'Dealing with a Difficult Customer',
  'Stuck in a Traffic Jam',
  'Computer Crash with Unsaved Work',
  'Lost or Misplaced Important Item',
  'Long Hold Time on Phone Call',
  'Slow Internet Connection',
  'Argument with a Loved One',
  'Missed Deadline or Opportunity',
  'Bad Weather on a Special Day',
  'Flight Delay or Cancellation',
  'Car Trouble or Breakdown',
  'Medical Test or Procedure Anxiety',
  'Financial Stress or Difficulty',
  'Bureaucratic Red Tape',
  'Unhelpful or Unresponsive Support',
  'Repetitive or Frustrating Task',
  'Unfair or Unjust Situation',
  'Lack of Control or Agency',
  'Unmet Expectations or Disappointment',
  'Feeling Overwhelmed or Burned Out',
  'Difficulty with a New Skill or Task',
  'Feeling Stuck or Trapped',
  'Unresolved Conflict or Issue',
  'Lack of Progress or Growth',
  'Feeling Undervalued or Unappreciated',
  'Dealing with a Know-It-All',
  'Unfair Criticism or Feedback',
  'Feeling Powerless or Helpless',
  'Repetitive Mistakes or Failures',
  'Uncooperative Team Members',
  'Unrealistic Expectations or Goals',
];

const instructions = [
  'Click get prompt, then take 3 minutes to write a list inspired by it.',
  'Click get prompt, then take 5 minutes to write a story about it using 3-5 words from your list.',
  'Click get prompt, then take 10 minutes to write another story inspired by your first story.',
];
const instructionsPara = document.querySelector('.instructions');
const promptText = document.querySelector('.prompt-text');
const startButton = document.querySelector('.start');
const stopButton = document.querySelector('.stop');
const timerSpan = document.querySelector('.timer');

let round = 0;
let timerId = null;
let timeLeft = 5;
// let timeLeft = 180; // 3 minutes in seconds

startButton.addEventListener('click', startTimer);
stopButton.addEventListener('click', newRound);
// Hide the stop button initially
stopButton.style.display = 'none';

function displayInstructions() {
  if (round === 0) {
    instructionsPara.textContent = instructions[0];
  }
  if (round === 1) {
    instructionsPara.textContent = instructions[1];
  }
  if (round === 2) {
    instructionsPara.textContent = instructions[2];
  }
}
function displayPrompt() {
  if (round === 0) {
    promptText.textContent =
      roundOnePrompts[Math.floor(Math.random() * roundOnePrompts.length)];
  } else if (round === 1) {
    promptText.textContent =
      roundTwoPrompts[Math.floor(Math.random() * roundTwoPrompts.length)];
  } else {
    promptText.textContent =
      roundThreePrompts[Math.floor(Math.random() * roundThreePrompts.length)];
  }
}
function stopTimer() {
  clearInterval(timerId);
  timerId = null;
  stopButton.style.display = 'inline-block';
  startButton.style.display = 'none';
}
function startTimer() {
  if (round === 0) {
    timeLeft = 180; // Set timer to 5 seconds for round 0
  } else if (round === 1) {
    timeLeft = 300; // Set timer to 10 seconds for round 1
  } else {
    timeLeft = 600; // Set timer to 15 seconds for round 2
  }
  timerId = setInterval(countDown, 1000);
  startButton.style.display = 'none';
  displayPrompt();
  updateTimerDisplay();
}

function countDown() {
  timeLeft--;
  updateTimerDisplay();
  if (timeLeft <= 0) {
    stopTimer();
    playAlarm();
  }
}

function updateTimerDisplay() {
  const minutes = Math.floor(timeLeft / 60);
  const seconds = timeLeft % 60;
  timerSpan.textContent = `${minutes}:${seconds.toString().padStart(2, '0')}`;
}

function playAlarm() {
  const audio = new Audio('./notification.mp3');
  audio.play();
}

function newRound() {
  stopButton.style.display = 'none';
  startButton.style.display = 'inline-block';
  if (round === 2) {
    round = 0;
  } else {
    round++;
  }
  promptText.textContent = '';
  displayInstructions();
}

displayInstructions();
